services:
  - type: web
    name: project-apsche
    env: docker
    branch: main
    autoDeploy: true
    plan: free
    dockerContext: .
    instanceType: starter
    envVars:
      - key: NODE_ENV
        value: production
